baseURL = 'http://janalourenci.github.io'
languageCode = 'en'
title = 'Janaína Di Lourenço'
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Janaína Di Lourenço"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:dilourenco.janaina@estudante.ufjf.br"

    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/janaina-di-lourenco-esteves"

    [[params.links]]
        iconorigin = "ai"
        iconset = "ai"
        icon = "academia"
        title = "Academia.edu
        url = "https://scholar.google.com"

    [[params.links]]
        iconorigin = "ai"
        iconset = "ai"
        icon = "lattes"
        title = "Lattes"
        url = "https://scholar.google.com"